tap "1password/tap"
tap "auth0/auth0-cli"
tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "charmbracelet/tap"
tap "cloudflare/cloudflare"
tap "derailed/k9s"
tap "dopplerhq/cli"
tap "grafana/grafana"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jumppad-labs/repo"
tap "localstack/tap"
tap "nikitabobko/tap"
tap "pkgxdev/made"
tap "puppetlabs/puppet"
tap "turbot/tap"
tap "waydabber/betterdisplay"
tap "weaveworks/tap"
brew "act"
brew "age"
brew "brotli"
brew "lz4"
brew "xz"
brew "zstd"
brew "webp"
brew "atuin"
brew "m4"
brew "autoconf"
brew "aws-iam-authenticator"
brew "aws-nuke"
brew "ca-certificates"
brew "libyaml"
brew "mpdecimal"
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "python@3.12"
brew "azure-cli"
brew "libssh2"
brew "libgit2"
brew "oniguruma"
brew "bat"
brew "btop"
brew "c-ares"
brew "libunistring"
brew "pcre2"
brew "xorgproto"
brew "libxau"
brew "libxdmcp"
brew "libxcb"
brew "libx11"
brew "libxext"
brew "certifi"
brew "clipboard"
brew "cloud-nuke"
brew "gmp"
brew "coreutils"
brew "cryptography"
brew "libnghttp2"
brew "rtmpdump"
brew "curl"
brew "direnv"
brew "doctl"
brew "doggo"
brew "eza"
brew "fd"
brew "fzf"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gdbm"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "libevent"
brew "libidn2"
brew "libtasn1"
brew "nettle"
brew "p11-kit"
brew "gnutls"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "goreleaser"
brew "graphviz"
brew "gum"
brew "helm"
brew "httpie"
brew "huggingface-cli"
brew "jq"
brew "k6"
brew "krew"
brew "kubecolor"
brew "kustomize"
brew "lazygit"
brew "libcbor"
brew "libfido2"
brew "libxfixes"
brew "libzip"
brew "linode-cli"
brew "ncurses"
brew "lnav"
brew "mas"
brew "minikube"
brew "mtr"
brew "zlib"
brew "mysql-client@8.0"
brew "nano"
brew "nmap"
brew "nushell"
brew "pcre"
brew "pkgconf"
brew "pyenv"
brew "python@3.11"
brew "qemu"
brew "rclone"
brew "ripgrep"
brew "rust"
brew "speedtest-cli"
brew "starship"
brew "telnet"
brew "temporal"
brew "thefuck"
brew "tree"
brew "trippy"
brew "usbutils"
brew "watch"
brew "wget"
brew "whois"
brew "wimlib"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-completions"
brew "auth0/auth0-cli/auth0"
brew "beeftornado/rmtree/brew-rmtree"
brew "derailed/k9s/k9s"
brew "dopplerhq/cli/doppler"
brew "grafana/grafana/alloy"
brew "hashicorp/tap/consul"
brew "hashicorp/tap/hcp"
brew "hashicorp/tap/nomad"
brew "hashicorp/tap/nomad-pack"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/waypoint"
brew "localstack/tap/localstack-cli"
brew "turbot/tap/steampipe"
cask "1password"
cask "1password-cli"
cask "angry-ip-scanner"
cask "arc"
cask "balenaetcher"
cask "bartender"
cask "betterdisplay"
cask "brave-browser"
cask "cloudflare-warp"
cask "cursor"
cask "discord"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "font-maple-mono"
cask "font-symbols-only-nerd-font"
cask "foxitreader"
cask "ghostty"
cask "google-drive"
cask "httpie"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "krisp"
cask "ledger-live"
cask "lm-studio"
cask "mongodb-compass"
cask "mullvadvpn"
cask "obs"
cask "ollama"
cask "orbstack"
cask "orion"
cask "raycast"
cask "rectangle-pro"
cask "shottr"
cask "soundsource"
cask "spacelauncher"
cask "spotify"
cask "steam"
cask "tailscale"
cask "telegram"
cask "visual-studio-code"
cask "wezterm"
cask "zed"
cask "zen-browser"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "Command X", id: 6448461551
mas "Cursor Pro", id: 1447043133
mas "Dato", id: 1470584107
mas "Day Progress", id: 6450280202
mas "Flighty", id: 1358823008
mas "HEIC Converter", id: 1294126402
mas "Hyperduck", id: 6444667067
mas "Keystroke Pro", id: 1572206224
mas "Klack", id: 6446206067
mas "Lungo", id: 1263070803
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Perplexity", id: 6714467650
mas "Photomator", id: 1444636541
mas "Pure Paste", id: 1611378436
mas "Speediness", id: 1596706466
mas "Structured", id: 1499198946
mas "Tot", id: 1491071483
mas "UTM", id: 1538878817
mas "Velja", id: 1607635845
mas "Windows App", id: 1295203466
