tap "1password/tap"
tap "auth0/auth0-cli"
tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "charmbracelet/tap"
tap "cloudflare/cloudflare"
tap "derailed/k9s"
tap "dopplerhq/cli"
tap "grafana/grafana"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jumppad-labs/repo"
tap "localstack/tap"
tap "pkgxdev/made"
tap "puppetlabs/puppet"
tap "turbot/tap"
tap "weaveworks/tap"
brew "act"
brew "age"
brew "brotli"
brew "lz4"
brew "xz"
brew "zstd"
brew "webp"
brew "atuin"
brew "readline"
brew "m4"
brew "autoconf"
brew "aws-iam-authenticator"
brew "aws-nuke"
brew "ca-certificates"
brew "mpdecimal"
brew "openssl@3"
brew "sqlite"
brew "python@3.11"
brew "azure-cli"
brew "libssh2"
brew "libgit2@1.7"
brew "oniguruma"
brew "bat"
brew "bdw-gc"
brew "bottom"
brew "bzip2"
brew "c-ares"
brew "pcre2"
brew "python@3.12"
brew "xorgproto"
brew "libxau"
brew "libxdmcp"
brew "libxcb"
brew "libx11"
brew "libxext"
brew "certifi"
brew "cryptography"
brew "certbot"
brew "cheat"
brew "clipboard"
brew "cloud-nuke"
brew "gmp"
brew "coreutils"
brew "libnghttp2"
brew "rtmpdump"
brew "curl"
brew "curlie"
brew "direnv"
brew "doctl"
brew "doggo"
brew "exercism"
brew "expat"
brew "libgit2"
brew "eza"
brew "fastfetch"
brew "fd"
brew "libevent"
brew "libunistring"
brew "libidn2"
brew "libtasn1"
brew "nettle"
brew "p11-kit"
brew "gnutls"
brew "icu4c"
brew "fzf"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gdbm"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "glances"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "graphviz"
brew "gum"
brew "helm"
brew "httpie"
brew "hub"
brew "libyaml"
brew "huggingface-cli"
brew "infracost"
brew "jq"
brew "k6"
brew "krew"
brew "kubecolor"
brew "kustomize"
brew "lazygit"
brew "lesspipe"
brew "lf"
brew "libcbor"
brew "libffi"
brew "libfido2"
brew "libiodbc"
brew "pkg-config"
brew "libpthread-stubs"
brew "libxfixes"
brew "libxdamage"
brew "libxml2"
brew "libzip"
brew "linode-cli"
brew "llama.cpp"
brew "llvm"
brew "llvm@17"
brew "ncurses"
brew "lnav"
brew "luajit-openresty"
brew "mas"
brew "minicom"
brew "minikube"
brew "mkcert"
brew "mtr"
brew "zlib"
brew "mysql-client@8.0"
brew "nano"
brew "nmap"
brew "nushell"
brew "openldap"
brew "parallel"
brew "pcre"
brew "poppler"
brew "portaudio"
brew "procs"
brew "pyenv"
brew "qemu"
brew "rclone"
brew "ripgrep"
brew "scrcpy"
brew "six"
brew "speedtest-cli"
brew "starship"
brew "superfile"
brew "switchaudio-osx"
brew "tailspin"
brew "tcl-tk"
brew "telnet"
brew "thefuck"
brew "tldr"
brew "tre"
brew "tree"
brew "ttyd"
brew "unar"
brew "volta"
brew "watch"
brew "wget"
brew "whois"
brew "wrk"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh"
brew "zsh-completions"
brew "auth0/auth0-cli/auth0"
brew "beeftornado/rmtree/brew-rmtree"
brew "charmbracelet/tap/wishlist"
brew "derailed/k9s/k9s"
brew "dopplerhq/cli/doppler"
brew "grafana/grafana/alloy"
brew "hashicorp/tap/boundary"
brew "hashicorp/tap/consul"
brew "hashicorp/tap/hcp"
brew "hashicorp/tap/nomad"
brew "hashicorp/tap/nomad-pack"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/vault"
brew "hashicorp/tap/waypoint"
brew "localstack/tap/localstack-cli"
brew "pkgxdev/made/pkgx"
brew "turbot/tap/steampipe"
brew "weaveworks/tap/eksctl"
cask "1password"
cask "1password-cli"
cask "angry-ip-scanner"
cask "arc"
cask "balenaetcher"
cask "bartender"
cask "brave-browser"
cask "cloudflare-warp"
cask "cursor"
cask "devutils"
cask "discord"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "font-blex-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-maple"
cask "font-symbols-only-nerd-font"
cask "foxitreader"
cask "google-drive"
cask "httpie"
cask "iterm2"
cask "karabiner-elements"
cask "krisp"
cask "ledger-live"
cask "mongodb-compass"
cask "obs"
cask "ollama"
cask "orbstack"
cask "orion"
cask "protonvpn"
cask "raycast"
cask "rectangle-pro"
cask "shottr"
cask "soundsource"
cask "spacelauncher"
cask "spotify"
cask "steam"
cask "tailscale"
cask "visual-studio-code"
cask "wezterm"
cask "zed"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "Command X", id: 6448461551
mas "CrystalFetch", id: 6454431289
mas "Cursor Pro", id: 1447043133
mas "Dato", id: 1470584107
mas "Day Progress", id: 6450280202
mas "Hyperduck", id: 6444667067
mas "Keystroke Pro", id: 1572206224
mas "Klack", id: 6446206067
mas "Lungo", id: 1263070803
mas "Pages", id: 409201541
mas "Pure Paste", id: 1611378436
mas "Second Clock", id: 6450279539
mas "Speediness", id: 1596706466
mas "Structured", id: 1499198946
mas "Tot", id: 1491071483
mas "UTM", id: 1538878817
mas "Velja", id: 1607635845
mas "Windows App", id: 1295203466
# vscode "1password.op-vscode"
# vscode "ahmadalli.vscode-nginx-conf"
# vscode "alefragnani.project-manager"
# vscode "astro-build.astro-vscode"
# vscode "be5invis.toml"
# vscode "bierner.github-markdown-preview"
# vscode "bierner.markdown-checkbox"
# vscode "bierner.markdown-emoji"
# vscode "bierner.markdown-footnotes"
# vscode "bierner.markdown-mermaid"
# vscode "bierner.markdown-preview-github-styles"
# vscode "bierner.markdown-yaml-preamble"
# vscode "bradlc.vscode-tailwindcss"
# vscode "catppuccin.catppuccin-vsc"
# vscode "catppuccin.catppuccin-vsc-icons"
# vscode "catppuccin.catppuccin-vsc-pack"
# vscode "christian-kohler.npm-intellisense"
# vscode "continue.continue"
# vscode "csstools.postcss"
# vscode "dbaeumer.vscode-eslint"
# vscode "dunstontc.vscode-docker-syntax"
# vscode "eamodio.gitlens"
# vscode "editorconfig.editorconfig"
# vscode "esbenp.prettier-vscode"
# vscode "evondev.indent-rainbow-palettes"
# vscode "formulahendry.auto-close-tag"
# vscode "formulahendry.auto-complete-tag"
# vscode "formulahendry.auto-rename-tag"
# vscode "foxundermoon.shell-format"
# vscode "ginfuru.better-nunjucks"
# vscode "github.copilot"
# vscode "github.copilot-chat"
# vscode "github.vscode-github-actions"
# vscode "gitpod.gitpod-flex"
# vscode "golang.go"
# vscode "graphql.vscode-graphql"
# vscode "graphql.vscode-graphql-syntax"
# vscode "hashicorp.hcl"
# vscode "hashicorp.terraform"
# vscode "icrawl.discord-vscode"
# vscode "jq-syntax-highlighting.jq-syntax-highlighting"
# vscode "kamikillerto.vscode-colorize"
# vscode "matthewpi.caddyfile-support"
# vscode "mattpocock.ts-error-translator"
# vscode "mechatroner.rainbow-csv"
# vscode "mgmcdermott.vscode-language-babel"
# vscode "miguelsolorio.fluent-icons"
# vscode "mikestead.dotenv"
# vscode "mindaro-dev.file-downloader"
# vscode "mrkaran.nomfmt"
# vscode "ms-azuretools.vscode-docker"
# vscode "ms-playwright.playwright"
# vscode "ms-python.debugpy"
# vscode "ms-python.python"
# vscode "ms-python.vscode-pylance"
# vscode "ms-vscode-remote.remote-containers"
# vscode "ms-vscode-remote.remote-ssh"
# vscode "ms-vscode-remote.remote-ssh-edit"
# vscode "ms-vscode-remote.remote-wsl"
# vscode "ms-vscode-remote.vscode-remote-extensionpack"
# vscode "ms-vscode.makefile-tools"
# vscode "ms-vscode.remote-explorer"
# vscode "ms-vscode.remote-repositories"
# vscode "ms-vscode.remote-server"
# vscode "ms-vsliveshare.vsliveshare"
# vscode "oderwat.indent-rainbow"
# vscode "prisma.prisma"
# vscode "redhat.ansible"
# vscode "redhat.vscode-yaml"
# vscode "run-at-scale.terraform-doc-snippets"
# vscode "rust-lang.rust-analyzer"
# vscode "steoates.autoimport"
# vscode "tailscale.vscode-tailscale"
# vscode "tamasfe.even-better-toml"
# vscode "tombonnike.vscode-status-bar-format-toggle"
# vscode "unifiedjs.vscode-mdx"
# vscode "unifiedjs.vscode-remark"
# vscode "usernamehw.errorlens"
# vscode "wakatime.vscode-wakatime"
# vscode "wholroyd.jinja"
# vscode "william-voyek.vscode-nginx"
# vscode "wix.vscode-import-cost"
# vscode "yatki.vscode-surround"
# vscode "yoavbls.pretty-ts-errors"
# vscode "yy0931.save-as-root"
