
# tap repositories and their packages

tap homebrew/core
brew act
brew atlantis
brew autoconf
brew awscli
brew azcopy
brew azure-cli
brew bat
brew bdw-gc
brew brotli
brew bzip2
brew c-ares
brew ca-certificates
brew cdktf
brew cloud-nuke
brew consul
brew curl
brew diff-so-fancy
brew doctl
brew envoy
brew exa
brew expat
brew fd
brew flyctl
brew fzf
brew gcc
brew gdbm
brew gettext
brew gh
brew git
brew git-delta
brew glances
brew gmp
brew gnupg
brew gnutls
brew go
brew guile
brew hub
brew icu4c
brew isl
brew lesspipe
brew libassuan
brew libcbor
brew libevent
brew libffi
brew libfido2
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libmpc
brew libnghttp2
brew libpthread-stubs
brew libssh2
brew libtasn1
brew libtermkey
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdamage
brew libxdmcp
brew libxext
brew libxfixes
brew libxml2
brew libzip
brew luajit
brew luajit-openresty
brew luv
brew lz4
brew m4
brew mas
brew mesa
brew mpdecimal
brew mpfr
brew msgpack
brew mysql-client
brew nano
brew ncurses
brew neovim
brew nettle
brew node
brew nomad
brew npth
brew openldap
brew openssl@1.1
brew openssl@3
brew p11-kit
brew packer
brew pcre
brew pcre2
brew pinentry
brew pkg-config
brew pyenv
brew python@3.10
brew python@3.8
brew python@3.9
brew readline
brew ripgrep
brew rtmpdump
brew rust
brew six
brew sqlite
brew starship
brew tcl-tk
brew terracognita
brew terraform
brew thefuck
brew tldr
brew tree-sitter
brew unbound
brew unibilium
brew waypoint
brew whois
brew xorgproto
brew xz
brew zlib
brew zsh
brew zsh-completions
brew zstd

tap homebrew/bundle

tap homebrew/cask-drivers
cask elgato-camera-hub
cask elgato-control-center
cask elgato-stream-deck
cask logitech-options

tap homebrew/cask-fonts
cask font-blex-mono-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-space-mono-nerd-font

tap homebrew/cask
cask 1password
cask balenaetcher
cask bartender
cask brave-browser
cask cloudflare-warp
cask cron
cask dbeaver-community
cask discord
cask docker
cask fig
cask google-chrome
cask google-drive
cask hookshot
cask iterm2
cask karabiner-elements
cask lastpass
cask notion
cask raycast
cask robo-3t
cask rocket-chat
cask signal
cask skype
cask slack
cask soundsource
cask spotify
cask tunnelbear
cask vagrant
cask visual-studio-code
cask warp
cask whatsapp

tap dopplerhq/cli
brew doppler

tap hashicorp/tap
brew boundary

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1470584107  Dato     (4.0.4)
appstore 1263070803  Lungo    (2.1.0)
appstore 1464122853  NextDNS  (1.5.1)
appstore 1176895641  Spark    (2.11.22)
appstore 1491071483  Tot      (1.4)
